name: EasyScoreboard
main: EasyScoreboard.EasyScoreboard
version: 1.0
api-version: 1.13
commands:
  easyscoreboard:
   description: Runs unit tests.
   permission: easyscoreboard.tester
   permission-message: You need easyscoreboard.tester in your groups permissions to execute that.
   usage: "Usage: /easyscoreboard test"